[build-system]
build-backend = "maturin"

[tool.poetry]
name = "rust-dtw"
<<<<<<< Updated upstream
version = "0.1.2"
=======
version = "0.1.8"
>>>>>>> Stashed changes
description = "A rust implementation of dynamic time warping with python bindings!"
license = "MIT"
readme = "README.md"
repository = "https://github.com/FL33TW00D/rustDTW"
authors = ["Christopher Fleetwood"]

[tool.poetry.dependencies]
numpy = ">=1.18"
python = ">=3.6"

[tool.poetry.dev-dependencies]
pytest = "^6.1"